### ISSUE TITLE
Can't build gem out-of-the-box, choctop.gemspec has errors

### ISSUE THREAD

**Issue by billymeltdown** [drnic/choctop#13]
From a fresh clone:

```
[wgray@Ryoan-ji]~/Documents/Sources/Git/choctop:master
$ gem build choctop.gemspec 
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)    ["assets/DefaultVolumeIcon.icns", "spec/spec.opts"] are not files
```

I'm vaguely aware that the gemspec is being generated automatically by some other process here, but it's not been documented. Makes it a touch difficult to send my fork to coworkers and say, "here, just gem build and install this," because it requires that I either give them the extra steps to fix the gemfile or I have to make the changes to the file myself in my fork, which is probably undesirable from the perspective of keeping my fork clean for upstream changes (e.g. I wouldn't want to include such changes in a pull request for some future patch).

**Comment by drnic** [comment]
Something wacky going on here. Investigating.

**Comment by drnic** [comment]
Ok, the Manifest.txt and gemspec are regenerated. I'll create a new ticket for updating documentation if its missing.

**Comment by drnic** [comment]
Ok, I've added development + release instructions. Can you check them out and see if anything is missing?

**Comment by billymeltdown** [comment]
Radical! Looks like we're almost there, the bundle step errored out looking for rake:

```
$ bundle
Fetching source index for http://rubygems.org/
Could not find rake-0.8.99.5 in any of the sources
```

In my macosx ruby setup, it looks like I've got rake --version 0.8.7, perhaps this is more an issue with my env?

**Comment by drnic** [comment]
ooh, a sneaky dependency. I've fixed it to be ~> 0.8.7 now.

**Comment by billymeltdown** [comment]
I spent a while hacking on this, my gems for /usr/bin/ruby appear to be up-to-date, and I can't seem to figure out where the rake dependency for 0.8.99.5 is coming from (nor can I find a way to properly upgrade /usr/bin/rake to a higher version than 0.8.7).

Should I be using a custom build of ruby, or macruby, instead of the snow leopard version?

**Comment by billymeltdown** [comment]
Ah, just saw your comment, nevermind previous post!

**Comment by billymeltdown** [comment]
Alrighty, changes came down alright, but didn't seem to fix the dependency issue, even with a fresh clone of master branch. Making the following changes fixed the problem right up for me, but I'm no bundler expert, so they could be inappropriate for other users:

```
diff --git a/Gemfile b/Gemfile
index b34aad3..dc68259 100644
--- a/Gemfile
+++ b/Gemfile
@@ -1,6 +1,6 @@
 source :gemcutter

-gem 'rake', '~> 0.8.7'
+gem 'rake', '>= 0.8.7'
 gem 'builder','2.1.2'
 gem 'awesome_print', '0.2.1'
 gem 'RedCloth', '4.2.3'
diff --git a/Gemfile.lock b/Gemfile.lock
index 24cd824..f6f3678 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -24,7 +24,7 @@ GEM
       hoe (>= 2.4.0)
       rubigen (>= 1.5.3)
       syntax (>= 1.0.0)
-    rake (0.8.99.5)
+    rake (0.8.7)
     rspec (2.4.0)
       rspec-core (~> 2.4.0)
       rspec-expectations (~> 2.4.0)
@@ -51,5 +51,5 @@ DEPENDENCIES
   escape (= 0.0.4)
   hoe (>= 2.6.1)
   newgem (>= 1.5.2)
-  rake (~> 0.8.7)
+  rake (>= 0.8.7)
   rspec (>= 2.0.0.beta)
```
